import { KYCApplication, AuditRecord, RiskMetrics } from '@/types/kyc';

export const mockUsers = [
  { email: 'user@example.com', password: 'Password123!', role: 'user' as const },
  { email: 'reviewer@example.com', password: 'Password123!', role: 'reviewer' as const },
  { email: 'admin@example.com', password: 'Password123!', role: 'admin' as const },
];

export const mockKYCApplications: KYCApplication[] = [
  {
    id: 'kyc-001',
    user_id: 'user-001',
    user_email: 'john.doe@example.com',
    status: 'IN_REVIEW',
    risk_score: 0.34,
    shap_explanation: [
      { feature: 'Face Match Confidence', shap_value: 0.18, feature_value: 0.87 },
      { feature: 'Document Age', shap_value: -0.12, feature_value: '2 years' },
      { feature: 'Address Verification', shap_value: 0.09, feature_value: 'Partial' },
      { feature: 'Transaction History', shap_value: 0.23, feature_value: 'Mismatch' },
      { feature: 'ID Quality Score', shap_value: -0.15, feature_value: 0.92 },
    ],
    face_match_score: 0.87,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
    documents: [
      {
        id: 'doc-001',
        kyc_id: 'kyc-001',
        doc_type: 'PASSPORT',
        file_path: '/uploads/passport-001.jpg',
        file_hash: 'abc123def456',
        extracted_data: {
          name: 'John Michael Doe',
          dob: '1990-05-15',
          documentNumber: 'P12345678',
          expiryDate: '2028-05-14',
          nationality: 'United States',
        },
        verified: true,
        uploaded_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: 'doc-002',
        kyc_id: 'kyc-001',
        doc_type: 'SELFIE',
        file_path: '/uploads/selfie-001.jpg',
        file_hash: 'xyz789ghi012',
        extracted_data: {},
        verified: true,
        uploaded_at: new Date(Date.now() - 3500000).toISOString(),
      },
    ],
    verifications: [
      {
        id: 'ver-001',
        kyc_id: 'kyc-001',
        event_type: 'document_upload',
        details: { doc_type: 'PASSPORT' },
        performed_by: 'system',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        tx_hash: '0x1a2b3c4d5e6f7890abcdef',
      },
      {
        id: 'ver-002',
        kyc_id: 'kyc-001',
        event_type: 'ocr_extraction',
        details: { success: true, fields_extracted: 6 },
        performed_by: 'system',
        timestamp: new Date(Date.now() - 3400000).toISOString(),
        tx_hash: '0x2b3c4d5e6f7890abcdef12',
      },
      {
        id: 'ver-003',
        kyc_id: 'kyc-001',
        event_type: 'face_match',
        details: { confidence: 0.87, threshold: 0.8 },
        performed_by: 'system',
        timestamp: new Date(Date.now() - 3200000).toISOString(),
        tx_hash: '0x3c4d5e6f7890abcdef1234',
      },
    ],
  },
  {
    id: 'kyc-002',
    user_id: 'user-002',
    user_email: 'jane.smith@example.com',
    status: 'APPROVED',
    risk_score: 0.12,
    shap_explanation: [
      { feature: 'Face Match Confidence', shap_value: -0.18, feature_value: 0.96 },
      { feature: 'Document Age', shap_value: -0.08, feature_value: '6 months' },
      { feature: 'Address Verification', shap_value: -0.12, feature_value: 'Verified' },
      { feature: 'Transaction History', shap_value: -0.05, feature_value: 'Clean' },
      { feature: 'ID Quality Score', shap_value: -0.10, feature_value: 0.95 },
    ],
    face_match_score: 0.96,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    documents: [
      {
        id: 'doc-003',
        kyc_id: 'kyc-002',
        doc_type: 'DRIVERS_LICENSE',
        file_path: '/uploads/license-002.jpg',
        file_hash: 'def456ghi789',
        extracted_data: {
          name: 'Jane Elizabeth Smith',
          dob: '1985-09-22',
          address: '123 Main St, San Francisco, CA',
          documentNumber: 'DL98765432',
          expiryDate: '2027-09-21',
        },
        verified: true,
        uploaded_at: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
    verifications: [],
  },
  {
    id: 'kyc-003',
    user_id: 'user-003',
    user_email: 'bob.wilson@example.com',
    status: 'REJECTED',
    risk_score: 0.78,
    shap_explanation: [
      { feature: 'Face Match Confidence', shap_value: 0.35, feature_value: 0.62 },
      { feature: 'Document Age', shap_value: 0.15, feature_value: '5 years' },
      { feature: 'Address Verification', shap_value: 0.22, feature_value: 'Failed' },
      { feature: 'Transaction History', shap_value: 0.28, feature_value: 'High Risk' },
      { feature: 'ID Quality Score', shap_value: 0.18, feature_value: 0.65 },
    ],
    face_match_score: 0.62,
    reviewer_comment: 'Face match confidence below acceptable threshold. Multiple verification failures.',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 5400000).toISOString(),
    documents: [],
    verifications: [],
  },
];

export const mockAuditRecords: AuditRecord[] = [
  {
    id: 'audit-001',
    entity_type: 'kyc_application',
    entity_id: 'kyc-001',
    event_hash: 'sha256:abc123def456...',
    tx_hash: '0x1a2b3c4d5e6f7890abcdef',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    details: { event: 'document_upload', status: 'success' },
  },
  {
    id: 'audit-002',
    entity_type: 'kyc_application',
    entity_id: 'kyc-002',
    event_hash: 'sha256:def456ghi789...',
    tx_hash: '0x2b3c4d5e6f7890abcdef12',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    details: { event: 'approval', risk_score: 0.12 },
  },
  {
    id: 'audit-003',
    entity_type: 'kyc_application',
    entity_id: 'kyc-003',
    event_hash: 'sha256:ghi789jkl012...',
    tx_hash: '0x3c4d5e6f7890abcdef1234',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    details: { event: 'rejection', reason: 'low_face_match' },
  },
];

export const mockRiskMetrics: RiskMetrics = {
  total_applications: 145,
  auto_approved: 98,
  manual_reviews: 32,
  rejected: 15,
  avg_risk_score: 0.28,
  avg_processing_time: 4.2,
};
